import React from "react";

function Modal({ closeModal }) {
	return (
		<div className="modal-bg">
			<div className="modal-wrapper container">
				<button className="close" onClick={() => closeModal(false)}>
					X
				</button>
				<h2>Terms & Conditions</h2>
				<p className="mx-0">Last Updated : October 21, 2021</p>
				<p className="mx-0">
					This website is operated by CRYPTOCREWZ. Throughout the site, the term
					« CRYPTOCREWZ », « we », « us » or « our » as the context may require,
					refer to CRYPTOCREWZ. By visiting our site and/or purchasing something
					from us, you engage in our Service and agree to be bound by the
					following terms and conditions.
				</p>
				<p className="mx-0">
					We reserve the right to update, change or replace any part of these
					Terms of services without prior written notice at any time, and it is
					your responsibility to periodically review these Terms of Uses to stay
					informed of updates. Any changes to the Terms will be in effect as of
					the « last updated » referenced on the site.
				</p>
				<p className="mx-0">
					Your continued use of this site after the last updated dates will
					constitute your acceptance of agreement.
				</p>
				<p className="mx-0">
					By visiting the website of our products merchants, in particular
					<a href="https://opensea.io">www.opensea.io</a>, you also engage and
					agree to be bound by their terms and conditions.
				</p>
				<p className="mx-0">
					This website is for informational purposes and serves as a binding
					contract for purchasers of CRYPTOCREWZ NFTs.
				</p>
				<p className="mx-0">
					Merchandise photos showing CRYPTOCREWZ apparel are mockups and design
					ideas only and not available for sale at the time of this writing.{" "}
				</p>
				<p className="mx-0">
					CRYPTOCREWZ is a generative collection of digital artwork (NFTs)
					housed and run on the Ethereum Network. Users and Collector of these
					NFTs are solely responsible for the safety and the management of their
					own private assets, which include but are not limited to Ethereum
					Wallets, validating all transactions and contracts generated by this
					website prior to and after purchases.
				</p>
				<p className="mx-0">
					Users certify through purchase that they understand that, as the
					CRYPTOCREWZ smart contract runs on the Ethereum network and is bound
					by their system and terms, there is no ability to undo, reverse, or
					restore any transactions.
				</p>
				<p className="mx-0">
					Any connected services included this website are provided “as is” and
					“as available” without any warranty of any kind. Use of this website
					constitutes your agreement that you are accepting sole responsibility
					for any and all transactions involving CRYPTOCREWZ digital
					collectibles.
				</p>
				<p className="mx-0">
					By agreeing to these Terms of Service, you represent that you are at
					least the age of majority in your state or province of residence.
				</p>
				<p className="mx-0">
					You may not use our products and/or services for any illegal or
					unauthorized purpose nor may you, in the use of the Service, violate
					any laws in your jurisdiction (including but not limited to copyright
					laws).
				</p>
				<h2>Ownership</h2>
				<p className="mx-0">
					When you purchase your CRYPTOCREWZ NFT, You Own the NFT : the
					ownership is transferred to you on the Ethereum blockchain for that
					individual piece of Art combination of traits and number. Ownership of
					the NFT is ruled by the smart contract and the Ethereum Network terms.
					We, CRYPTOCREWZ, have no ability to alter, freeze, seize or modify the
					ownership of any CRYPTOCREWZ NFT.
				</p>
				<h2>Gas Fees</h2>
				<p className="mx-0">
					Every transaction on the Ethereum Blockchain requires the payment of a
					transaction fee (a “Gas Fee”). The Gas Fees fund the network of
					computers that run the decentralized Ethereum Blockchain. This means
					that you will need to pay a Gas Fee for each transaction that you
					instigate via the purchase of a CryptoCrewz NFT. Except as otherwise
					expressly set forth in these Terms, you will be solely responsible to
					pay any Gas Fee for any transaction that you instigate via the
					purchase of a CryptoCrewz NFT.
				</p>
				<h2>Personal Usage</h2>
				<p className="mx-0">
					User License to Art: Subject to your continued compliance with these
					Terms, we grant you a worldwide, non-exclusive, non-transferable,
					royalty-free license to use, copy, and display the Art for your
					purchased NFT, solely for the following purposes: (a) for your own
					personal, non-commercial use; (b) as part of a marketplace that
					permits the purchase and sale of your purchased NFT, provided that the
					marketplace cryptographically verifies each NFT’s owner’s rights to
					display the Art for their NFT to ensure that only the actual owner can
					display the Art; or (c) as part of a third party website or
					application that permits the inclusion, involvement, or participation
					of your NFT, provided that the website/application cryptographically
					verifies each NFT’s owner’s rights to display the Art for their NFT to
					ensure that only the actual owner can display the Art, and provided
					that the Art is no longer visible once the owner of the NFT leaves the
					website/application.
				</p>
				<h2>Restrictions on Ownership</h2>
				<p className="mx-0">
					You agree that you may not, nor permit any third party to do or
					attempt to do any of the foregoing without our express prior written
					consent in each case: (a) modify the Art for your NFT in any way,
					including, without limitation, the shapes, designs, drawings,
					attributes, or color schemes; (b) use the Art for your NFT to
					advertise, market, or sell any third party product or service; (c) use
					the Art for your NFT in connection with images, videos, or other forms
					of media that depict hatred, intolerance, violence, cruelty, or
					anything else that could reasonably be found to constitute hate speech
					or otherwise infringe upon the rights of others; (d) use the Art for
					your NFT in movies, videos, or any other forms of media, except to the
					limited extent that such use is expressly permitted in these Terms or
					solely for your own personal, non-commercial use; (e) sell, distribute
					for commercial gain (including, without limitation, giving away in the
					hopes of eventual commercial gain), or otherwise commercialize
					merchandise that includes, contains, or consists of the Art for your
					NFT; (f) attempt to trademark, copyright, or otherwise acquire
					additional intellectual property rights in or to the Art for your NFT;
					or (g) otherwise utilize the Art for your NFT for your or any third
					party’s commercial benefit.
				</p>
				<p className="mx-0">
					Further, CRYPTOCREWZ reserves the right to use ANY character,
					including : print or digital advertising, or any purely creative media
					in support of the CRYPTOCREWZ community and message.
				</p>
				<p className="mx-0">
					If at any time you trade, donate, giveaway, transfer or otherwise
					dispose of your NFT for any reason, the license granted above will
					immediately expire, without notice, and you will have no further right
					in or to the artwork of this NFT.
				</p>
				<h2>CRYPTOCREWZ IP</h2>
				<p className="mx-0">
					Other than the rights to the Art, nothing gives you any rights to any
					other trademarks or other intellectual property rights belonging to
					CRYPTOCREWZ including, without limitation CRYPTOCREWZ and the
					associated logos. All of these rights are expressly reserved in the
					name of CRYPTOCREWZ.
				</p>
				<h2>Feedback</h2>
				<p className="mx-0">
					You can submit comments, bug reports, ideas about the site or the
					project. By submitting any feedback, you agree that we are free to use
					them in any way we choose without additional compensation to you and
					you hereby grant us a perpetual, irrevocable, nonexclusive worldwide
					licence to incorporate and use the feedback for any purpose.
				</p>
				<h2>Credits</h2>
				<p className="mx-0">
					Website designed and developed by{" "}
					<a
						href="https://illusive.dribble.com"
						target="_blank"
						rel="noreferrer"
					>
						Anthony Zayne.
					</a>
				</p>
			</div>
		</div>
	);
}

export default Modal;
